services:

  redis:
    image: redis:7-alpine
    container_name: vive-ai-photobooth-redis
    restart: unless-stopped

    ports:
      - "6379:6379"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: vive-ai-photobooth-backend

    ports:
      - "8000:8000"

    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: sqlite:////app/storage/vive_photobooth.db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

    volumes:
      - ./backend/storage:/app/storage

    depends_on:
      - redis


  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: vive-ai-photobooth-celery

    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: sqlite:////app/storage/vive_photobooth.db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

    volumes:
      - ./backend/storage:/app/storage

    depends_on:
      - redis
      - backend

    command: >
      celery
      -A app.tasks
      worker
      --loglevel=info


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: vive-ai-photobooth-frontend

    ports:
      - "5173:80"

    restart: unless-stopped

    depends_on:
      - backend